#Page Settings
title: 周明的博客
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
filter: 'category' # Choose 'tag' or 'category' as filter in sidebar.
# Author Settings
author: 
  name: Gary 
  about: I am a web developer focusing on front-end development. Always hungry to keep learning. # add description
  github: SDriedFish # add your Github handle
  author-img: gary.jpg
  email: 540195111@qq.com
  qrcode: qrcode.jpg
  facebook: # add your Facebook handle
# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji